uwdreamproject/DreamSIS

app/controllers/rsvp_controller.rb
app/controllers/welcome_controller.rb
app/models/people/mentor.rb
app/views/rsvp/_rsvp_button.html.erb

Updates needed to make the generated Excel document for a term provide accurate mentor information.

WIN2014 Mentor helper method updates and RSVP Updates

---

app/models/people/mentor.rb

Final fixes that allow for proper report generation. Also fixes bug that may make mentors think section signup fails.

Fix mentor report errors

---

app/assets/stylesheets/dreamsis.css
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/models/college_application.rb
app/models/users/pubcookie_user.rb
app/views/activity_logs/weekly_summary.html.erb
app/views/shared/_nav.html.erb
app/views/users/edit.html.erb
config/initializers/formtastic.rb
config/routes.rb

Fixing the most high-priority bugs at the beginning of the year:
* PubcookieUser objects can't be edited and aren't assigned UID and provider attributes
* Can't view details of Volunteers
* Form errors not displaying properly

Early Jan 2015 bug fixes

---

app/models/event_group.rb

@mattharris5 Not sure what kind of work you're doing on the cluster, but this needs to be deployed before morning, as it seems to be breaking RSVPs when not yet logged in.

Fix future events audience handling

---

app/controllers/mentor_signup_controller.rb
app/controllers/participants_controller.rb

Some minor changes affecting access to pages.

Participant Group bug and mentor_term change

---

app/views/mentors/_mentor_onboarding.html.erb
app/views/mentors/_onboarding_form.html.erb

@mattharris5 The WATCH site changed their form to only allow middle initials instead of full names, not sure if anyone else is currently using this feature.

Change WATCH checks to use middle initials

---

app/assets/javascripts/driver_form.js
app/controllers/mentors_controller.rb
app/models/people/mentor.rb
app/views/mentors/_mentor_driver.html.erb
app/views/mentors/_mentor_onboarding.html.erb
app/views/mentors/_van_driver_table.html.erb
app/views/mentors/van_drivers.html.erb
app/views/mentors/van_drivers.js.erb

@mattharris5 could you take a look at these? It would be nice to have this pushed before the HSL meeting tonight.

Driver Page Improvements

---

app/models/customer.rb
app/views/mentors/show.html.erb

Urgent update for showing conduct form signing status

Show conduct form signing status on mentor page

---

app/models/uw_web_services/course_section_resource.rb
app/views/mentors/_mentor_participant.html.erb
app/views/participants/_sidebar.html.erb

Hey @mattharris5, do these changes look OK? HSLs have already had the authorization to perform these actions, this just updates to UI to give them the proper buttons.

Participant management for HSLs

---

app/assets/javascripts/mentor_term_groups.js
app/controllers/activity_logs_controller.rb
app/controllers/college_applications_controller.rb
app/controllers/locations_controller.rb
app/controllers/mentor_term_groups_controller.rb
app/controllers/mentors_controller.rb
app/controllers/participants_controller.rb
app/controllers/scholarship_applications_controller.rb
app/controllers/scholarships_controller.rb
app/models/participant_group.rb
app/models/people/mentor.rb
app/views/events/show.html.erb
app/views/mentor_term_groups/show.html.erb
app/views/mentors/event_status.html.erb
config/routes.rb

Including high/repeat offenders

Various bug fixes

---

app/views/mentors/event_status.html.erb

Basic updates to make the main functionality work. This code still
needs significant refactoring, and potentially the ability to join
a rsvpd/attended query.

Update mentor event status page to use jQuery

---

app/assets/javascripts/event_status.js
app/assets/stylesheets/dreamsis.css.erb
app/views/mentors/event_status.html.erb

Adds a button to show only enrolled mentors, and also changes the styling to make it clear which
criterion is currently active. Still needs refactored.

Further update events page

---

app/assets/javascripts/attendance.js
app/assets/javascripts/reports.js
app/assets/stylesheets/dreamsis.css.erb
app/controllers/participants_controller.rb
app/helpers/participants_helper.rb
app/models/college_application.rb
app/models/event.rb
app/models/people/participant.rb
app/models/people/person.rb
app/models/reports/college_applications_report.rb
app/models/reports/report.rb
app/models/reports/test_scores_report.rb
app/models/test_score.rb
app/models/visit.rb
app/views/participants/_export_actions.html.erb
app/views/participants/_report_select.html.erb
app/views/participants/_sidebar.html.erb
app/views/participants/index.js.erb
app/views/participants/reports/_attendance_summaries.html.erb
app/views/participants/reports/_attendance_summaries_header.html.erb
app/views/participants/reports/_rosters.html.erb
app/views/participants/reports/_test_score_summaries.html.erb
app/views/participants/reports/_test_score_summaries_header.html.erb
app/views/participants/reports/_wrapper.html.erb
db/migrate/20150605230416_add_deleted_at_to_mentor_terms_if_needed.rb
db/schema.rb

Adds two major reporting improvements:
* Conditional Excel exports - Excel output will change based on the type of report displayed. If you change to Test Scores, the Excel download will provide test scores for the participants in the current view instead of the normal Excel output. Same with college applications.
* A new Attendance report view - easily view and edit attendance for the participants you’re viewing for the past 5 most recent events by switching the Display dropdown.

Reporting improvements

---

config/api-keys.example.yml

Just to keep things up to date

Add mandrill fields to api-keys.example

---

app/models/customer.rb
app/views/customers/show.html.erb

Made two changes from the previous version of customer.rb (use of case-when) and show.html.erb

Shows driver training and background checks validity lengths

---

app/controllers/participants_controller.rb

https://codeclimate.com/repos/51532b76f3ea007746006907/security/9aa6d496
6a43d9b8855af8db4e089e00

Removes denial of service vulnerability

---

app/assets/javascripts/autocompletes.js
app/controllers/event_attendances_controller.rb
app/controllers/mentors_controller.rb
app/views/event_attendances/_person.html.erb
app/views/event_attendances/checkin.html.erb
app/views/mentors/_fields.html.erb
app/views/mentors/show.html.erb
config/routes.rb
db/migrate/20151112183412_add_index_to_event_attendance.rb
db/schema.rb

Key improvement is reduction in total number of sql queries from N+1 to
3.

Refactor event check-in autocomplete queries

---

app/controllers/application_controller.rb
app/models/customer.rb
app/models/people/person.rb
app/views/event_attendances/_person.html.erb

Biggest improvement is storing the current customer in the current thread to avoid multiple checks

More autocomplete performance enhancements

---

app/assets/javascripts/tabs.js
app/assets/stylesheets/dreamsis.css.erb
app/controllers/participants_controller.rb
app/models/people/parent.rb
app/models/people/participant.rb
app/models/reports/parents_report.rb
app/views/parents/_fields.html.erb
app/views/participants/fields/_contact.html.erb
app/views/participants/reports/_parent.html.erb
app/views/participants/reports/_parents.html.erb
app/views/participants/reports/_parents_header.html.erb
app/views/participants/reports/_wrapper.html.erb

Adds new parent/contact list view and ability to export to Excel.

Export parents and contacts

---

.gitignore
app/helpers/mentors_helper.rb
app/models/people/person.rb
app/views/mentors/_watch_bookmarklet.js
app/views/mentors/onboarding.html.erb

Updates the WATCH bookmarklet for the latest changes to the WATCH system, and switches to using JSON for data exchange. Much better than before!
The new bookmarklet code is a bit trickier than before because the new WATCH UI requires you to enter each name one at a time and add them to a queue for processing. To accommodate, this javascript enters each person one by one and emulates clicking the “Add” button.

Use JSON for WATCH and update to new format

---

app/views/mentors/_watch_bookmarklet.js

Primarily improves error handling, and uses jQuery UI to allow
mid-process changes to the JSON entries if the WATCH website returns
any validation errors.

Interactive WATCH error handling

---

app/models/users/user.rb
app/views/users/edit.html.erb

And allow admins to update other users to become admins.
@mattharris5 Does the `allow_nil` fix work, or should we consider something else?

Fix user update page

---

app/controllers/mentors_controller.rb
app/controllers/participants_controller.rb
app/models/people/participant.rb
app/models/uw_web_services/uw_web_resource.rb

@aayush19saxena @mattharris5 I'm just going to be making some simple fixes to speed things up where necessary. For example, mentor fullname search has a bunch of low hanging fruit that can be cleaned up.

Last-minute performance fixes

---

Gemfile
Gemfile.lock
app/models/location.rb
app/models/people/mentor.rb
app/models/people/participant.rb
db/migrate/20160531083419_create_friendly_id_slugs.rb
db/migrate/20160531085718_add_slug_to_people.rb
db/migrate/20160607061512_add_slug_to_location.rb
db/schema.rb

Hey @mattharris5 @mitchellharper12- I have added some basic functionality for friendly_id to run. Currently, it is set on mentors' and participants' `fullname`. Feel free to go over through the PR!

Friendly_id to objects

---

db/seeds.rb

Didn't notice it while developing the feature before. Just a small fix in the seeds.

Helptext shows up for Mentors
